# Generated by Django 5.0.3 on 2024-04-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_user_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.CharField(default='ADMIN', max_length=200),
        ),
    ]
